version: '3.8'

services:
  nacos-node1:
    image: nacos/nacos-server:v2.3.0
    container_name: nacos-node1
    restart: always
    environment:
      PREFER_HOST_MODE: hostname
      MODE: cluster
      NACOS_APPLICATION_PORT: 8848
      NACOS_SERVERS: 192.168.100.11:8848 192.168.100.12:8848 192.168.100.13:8848
      MYSQL_SERVICE_HOST: 192.168.100.11
      MYSQL_SERVICE_PORT: 3306
      MYSQL_SERVICE_DB_NAME: nacos_config
      MYSQL_SERVICE_USER: nacos
      MYSQL_SERVICE_PASSWORD: nacos123456
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
      NACOS_AUTH_ENABLE: true
      NACOS_AUTH_TOKEN: SecretKey012345678901234567890123456789012345678901234567890123456789
      NACOS_AUTH_IDENTITY_KEY: nacos
      NACOS_AUTH_IDENTITY_VALUE: nacos
      JVM_XMS: 2g
      JVM_XMX: 2g
      JVM_XMN: 1g
      JVM_MS: 128m
      JVM_MMS: 320m
      JVM_EXTRA_OPTS: '-XX:+UseG1GC -XX:MaxGCPauseMillis=200'
      TZ: Asia/Shanghai
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    volumes:
      - ./logs/node1:/home/nacos/logs
      - ./config/application.properties:/home/nacos/conf/application.properties:ro
    networks:
      - nacos-network
    depends_on:
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/v1/console/health/readiness"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  mysql:
    image: mysql:8.0
    container_name: nacos-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: nacos123456
      MYSQL_DATABASE: nacos_config
      MYSQL_USER: nacos
      MYSQL_PASSWORD: nacos123456
      TZ: Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/nacos-mysql.sql:/docker-entrypoint-initdb.d/nacos-mysql.sql:ro
      - ./mysql/conf:/etc/mysql/conf.d:ro
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --explicit_defaults_for_timestamp=true
      - --lower_case_table_names=1
      - --max_allowed_packet=128M
      - --sql-mode=STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
    networks:
      - nacos-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "nacos", "-pnacos123456"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

networks:
  nacos-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24